---
- name: Ensure MySQL service is running
  ansible.builtin.service:
    name: "{{ 'mysqld' if ansible_facts['os_family'] == 'RedHat' else 'mysql' }}"
    state: started
    enabled: yes

- name: Secure MySQL installation
  include_tasks: secure-installation.yml

