---
- name: Check MySQL version
  command: "{{ mysql_bin }} --version"
  register: mysql_version
  become: yes

- name: Debug MySQL version
  debug:
    msg: "MySQL version: {{ mysql_version.stdout }}"

