---
- name: Ensure MySQL users are present.
  community.mysql.mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default(false) }}"
    encrypted: "{{ item.encrypted | default(false) }}"
    column_case_sensitive: "{{ item.case_sensitive | default(false) }}"
    update_password: "{{ item.update_password | default('always') }}"
    login_user: "{{ mysql_root_user }}"       # <-- add this
    login_password: "{{ mysql_root_password }}" # <-- add this
  with_items: "{{ mysql_users }}"
  become: true
  no_log: "{{ mysql_hide_passwords }}"
  when: skip_mysql_users is not defined

