mysql_root_password: "$077Timzy2557!"
mysql_databases:
  - name: tooling
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: webaccess
    host: " 172.31.2.0/24" # Webserver subnet cidr
    password: Admin123$
    priv: "tooling.*:ALL,GRANT"
