# roles/mysql/vars/main.yml
mysql_root_password: ""
mysql_database:
  - name: homestead
    encoding: utf8
    collation: utf8_genral_cli
mysql_users:
  - name: homestead
    host: "%"
    password: sePret^i1
    priv: "*.*ALL"
